### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by joakimfischer** [kipe/nordpool#1]
This is a question and not an issue;

Where can I found documentation to the API you use? I would like to know how I can tweak the call to the API with more parameters. Right now, all I have is below... but it would be nice to set startDate, areas and control returning fields as well... but I cannot find documentation for this anywhere. All I find is Nordpool Developer Portal but this is not included there that I can find.

http://www.nordpoolspot.com/api/marketdata/page/13?currency=SEK&endDate=01-08-2016

**Comment by kipe** [comment]
There is no documentation, as the API isn't exactly public :fearful: 
I'd assume there's no parameters for such things, otherwise I would have most probably implemented them...

But thanks for the heads up on Nordpool Developer Portal, I'll have to check it out. Might be possible to create a library using the official APIs :+1:

**Comment by joakimfischer** [comment]
Ok :) Thanks

Their API is all xml and I think its mostly for traders.. cant really get my examples to work out so I am dropping it now. Will use your code and URL as template instead.
